import { Item } from './item'

export const ITEMS: Item[] =[
  {
    id: 1,
    title: "Bun cha",
    category: "Breakfast",
    price: 15,
    img: "../assets/Picture/buncha.jpg",
    desc: "Bun cha rat ngon ban nen thu",
  },
  {
    id: 2,
    title: "Banh xeo",
    category: "Dinner",
    price: 10,
    img: "../assets/Picture/banhxeo.jpg",
    desc: "Banh xeo dac san mien trung",
  },
  {
    id: 3,
    title: "Bap xao",
    category: "Snack",
    price: 5,
    img: "../assets/Picture/bapxao.jpg",
    desc: "Bap xao cuc ngot cuc ngon",
  },
  {
    id: 4,
    title: "Cut lon",
    category: "Snack",
    price: 10,
    img: "../assets/Picture/cutlon.jpg",
    desc: "Cut lon la mon an vat khong the thieu",
  },
  {
    id: 5,
    title: "Dau phu",
    category: "Dinner",
    price: 20,
    img: "../assets/Picture/dauphu.jpg",
    desc: "Dau phu cay nhoi thit",
  },
  {
    id: 6,
    title: "Ga chien mam",
    category: "Dinner",
    price: 25,
    img: "../assets/Picture/gachienmam.jpg",
    desc: "Ga chien gion sot nuoc mam",
  },
  {
    id: 7,
    title: "My quang",
    category: "Breakfast",
    price: 20,
    img: "../assets/Picture/myquang.jpg",
    desc: "My quang mon ngon Viet Nam",
  },
  {
    id: 8,
    title: "Suon xao",
    category: "Dinner",
    price: 25,
    img: "../assets/Picture/suonxaochuangot.jpg",
    desc: "Suon xao vua chua vua ngot",
  },
  {
    id: 9,
    title: "Banh beo",
    category: "Breakfast",
    price: 10,
    img: "../assets/Picture/banhbeo.jpg",
    desc: "Banh beo dac san dat Hue",
  },
  {
    id: 10,
    title: "Banh uot",
    category: "Breakfast",
    price: 10,
    img: "../assets/Picture/banhuot.jpg",
    desc: "Suon xao vua chua vua ngot",
  },
  {
    id: 11,
    title: "Coca Cola",
    category: "Drink",
    price: 5,
    img: "../assets/Picture/coca.jpg",
    desc: "Thuc uong giai khat duoc ua chuong",
  },
  {
    id: 12,
    title: "Com tam",
    category: "Lunch",
    price: 15,
    img: "../assets/Picture/comtam.jpg",
    desc: "Com tam ngon tuyet voi",
  },
  {
    id: 13,
    title: "Cafe",
    category: "Drink",
    price: 10,
    img: "../assets/Picture/cafe.jpg",
    desc: "Thuc uong giai khat giup ban tinh tao",
  },
  {
    id: 14,
    title: "Xoi ga",
    category: "Breakfast",
    price: 15,
    img: "../assets/Picture/xoiga.jpg",
    desc: "Mon an quen thuoc voi hoc sinh",
  },
  {
    id: 15,
    title: "Tra sua",
    category: "Drink",
    price: 50,
    img: "../assets/Picture/milktea.jpg",
    desc: "Thuc uong ua thich cua cac ban nu",
  },
  {
    id: 16,
    title: "My tom",
    category: "Lunch",
    price: 25,
    img: "../assets/Picture/mytom.jpg",
    desc: "Mon an don gian",
  },
  {
    id: 17,
    title: "My tuong den",
    category: "Lunch",
    price: 40,
    img: "../assets/Picture/mytuongden.jpg",
    desc: "Mon an noi tieng cua Han Quoc",
  },
  {
    id: 18,
    title: "Banh trang tron",
    category: "Snack",
    price: 20,
    img: "../assets/Picture/banhtrantron.jpg",
    desc: "Do an vat tuoi tho cua moi nguoi",
  }
]
